package coop.pratice.domain;

// Generated May 14, 2015 3:23:04 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderDetail generated by hbm2java
 */
@Entity
@Table(name = "order_detail", schema = "public")
public class OrderDetail implements java.io.Serializable {

	private int id;
	private Order order;
	private Product product;
	private BigDecimal qty;
	private Double listTotal;

	public OrderDetail() {
	}

	public OrderDetail(int id, Order order, Product product) {
		this.id = id;
		this.order = order;
		this.product = product;
	}

	public OrderDetail(int id, Order order, Product product, BigDecimal qty,
			Double listTotal) {
		this.id = id;
		this.order = order;
		this.product = product;
		this.qty = qty;
		this.listTotal = listTotal;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false)
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "qty", precision = 131089, scale = 0)
	public BigDecimal getQty() {
		return this.qty;
	}

	public void setQty(BigDecimal qty) {
		this.qty = qty;
	}

	@Column(name = "list_total", precision = 17, scale = 17)
	public Double getListTotal() {
		return this.listTotal;
	}

	public void setListTotal(Double listTotal) {
		this.listTotal = listTotal;
	}

}
