package coop.pratice.domain;

// Generated May 14, 2015 3:23:04 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", schema = "public")
public class Product implements java.io.Serializable {

	private int id;
	private Producttype producttype;
	private String name;
	private Double price;
	private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);
	private Set<ProductImg> productImgs = new HashSet<ProductImg>(0);

	public Product() {
	}

	public Product(int id, Producttype producttype) {
		this.id = id;
		this.producttype = producttype;
	}

	public Product(int id, Producttype producttype, String name, Double price,
			Set<OrderDetail> orderDetails, Set<ProductImg> productImgs) {
		this.id = id;
		this.producttype = producttype;
		this.name = name;
		this.price = price;
		this.orderDetails = orderDetails;
		this.productImgs = productImgs;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_id", nullable = false)
	public Producttype getProducttype() {
		return this.producttype;
	}

	public void setProducttype(Producttype producttype) {
		this.producttype = producttype;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", precision = 17, scale = 17)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<OrderDetail> getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set<OrderDetail> orderDetails) {
		this.orderDetails = orderDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<ProductImg> getProductImgs() {
		return this.productImgs;
	}

	public void setProductImgs(Set<ProductImg> productImgs) {
		this.productImgs = productImgs;
	}

}
